app:
  page_title: "AI Quizup"
  page_icon: "ğŸ¤–"
  title: "ğŸ¤– AI Quizup ğŸ“š"
  onboarding:
    - "Â¡Bienvenido a mi aplicaciÃ³n de quiz! ğŸ‰"
    - "AquÃ­ encontrarÃ¡s un divertido desafÃ­o de preguntas y respuestas para probar tus conocimientos. ğŸ§ "
    - "Â¡Es muy fÃ¡cil de usar! Simplemente sigue estos simples pasos:"
    - "1ï¸âƒ£ Utiliza los botones `Pregunta previa` y `Pregunta siguiente` para navegar entre las preguntas de manera sencilla."
    - "2ï¸âƒ£ Lee atentamente cada pregunta y selecciona la respuesta que consideres correcta en la lista de opciones de selecciÃ³n mÃºltiple. ğŸ—’ï¸âœï¸"
    - "3ï¸âƒ£ Â¡No te preocupes si te equivocas! En el contador podrÃ¡s ver cuÃ¡ntas preguntas has respondido correctamente y cuÃ¡ntas te has equivocado. ğŸ“ˆğŸ‘âŒ"
    - "4ï¸âƒ£ DespuÃ©s de responder, aparecerÃ¡ una caja de texto con una explicaciÃ³n detallada sobre por quÃ© una de las respuestas listadas es correcta. AsÃ­ podrÃ¡s aprender y mejorar tus conocimientos en cada intento. ğŸ“šğŸ”"
    - "Â¡Y eso es todo! Ahora puedes disfrutar de la emociÃ³n de aprender mientras juegas. ğŸ¤©ğŸ“²"
    - "Â¿EstÃ¡s listo para comenzar? Haz clic en el botÃ³n para empezar a responder las preguntas y demostrar tus habilidades. Â¡Buena suerte y que te diviertas! ğŸŒŸğŸ¯"
