app:
  page_title: "Witamy w quizie PBC"
  page_icon: "ğŸ“ˆ"
  title: "Witamy w quizie PBCğŸ“š!"
  onboarding:
    - "Quiz skÅ‚ada sie z 8 pytaÅ„"
  quiz:
    prev: "â¬…ï¸"
    next: "â¡ï¸"
    choice: "Odpowiedzi:"
    correct: "Twoja odpowiedÅº jest prawidÅ‚owağŸ¥³"
    wrong: "Twoja odpowiedÅº jest nieprawidÅ‚owağŸ˜” PrawidÅ‚owa odpowiedÅº to: "
    explanation: "WyjÅ›nienie ğŸ‘©â€ğŸ«"
    counter_right: "âœ… PrawidÅ‚owe odpowiedzi: "
    counter_wrong: "âŒ NieprawidÅ‚owe odpowiedzi: "
    submit: "SprawdÅº odpowiedÅº"
    over_message: "## Quiz ukoÅ„czony! ğŸ‘ "
    score_message: "### Punktacja: "
